[project]
name = "linkedinjobpostingscurriculummodifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docx2pdf>=0.1.8",
    "docxtpl>=0.20.1",
    "openai>=1.99.9",
    "python-dotenv>=1.1.1",
    "reportlab>=4.4.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-timeout>=2.4.0",
]
